### ISSUE TITLE
Problem during upload - File descriptor??

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#59] opened 2011-10-01 12:21 UTC
Currently unable to upload data sets to frisian-stories server.

11:08:52,219 INFO  ~ Accepting file 8ABCAAD9C62D57BBC0191ABFE79A7E90__hints.txt for DataSet FriesMuseum
11:08:52,439 ERROR ~ 

@680kc8h12
Internal Server Error (500) for request POST /frisianstories/dataset/sip-creator/submit/FriesMuseum/8ABCAAD9C62D57BBC0191ABFE79A7E90__hints.txt?accessKey=27281a59745247fc8a870296a87542

Oops: IOException
An unexpected error occured caused by exception IOException: Bad file descriptor

play.exceptions.UnexpectedException: Unexpected Error
        at play.libs.IO.readContent(IO.java:185)
        at controllers.SipCreatorEndPoint$.receiveHints(SipCreatorEndPoint.scala:183)
        at controllers.SipCreatorEndPoint$.acceptFile(SipCreatorEndPoint.scala:145)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:496)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        at Invocation.HTTP Request(Play!)
Caused by: java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:198)
        at play.libs.IO.readContent(IO.java:180)
        ... 8 more

**Comment by manuelbernhardt** [comment] 2011-10-01 16:52
I investigated this now for nearly 2 hours and ended up writing to the
Play ML. In short, it looks like the request.body can't be accessed
directly anymore, and I have a hard time figuring out why. The data is
there somewhere, albeit as a "body" request parameter, which is
unsuitable for parsing INTs and large data (source). I hope to get a
quick answer to that one.

On Sat, Oct 1, 2011 at 2:21 PM, Gerald de Jong
reply@reply.github.com
wrote:

**Comment by geralddejong** [comment] 2011-10-01 17:54
It's at these moments that it is a little uncomfortable on the bleeding edge of a new technology.

**Comment by manuelbernhardt** [comment] 2011-10-01 19:00
Yeah that is an inconvenience of being on on the latest version - if
that is the cause in the end. I got a reply and Morten (one of the
core devs from Norway) will have a look at this. In the meanwhile I
will write a workaround tomorrow so that we can get to work.
We also should have a set of tests to cover the API

**Comment by manuelbernhardt** [comment] 2011-10-01 22:37
This is now submitted at

https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1146-requestbody-does-not-stream-body-contents-anymore

I will make a separate branch for the ingestion with a previous version of play tomorrow.

**Comment by geralddejong** [comment] 2011-10-02 06:48
Nice work!

**Comment by manuelbernhardt** [comment] 2011-10-02 10:20
Ok, this took me the better part of the morning, but play works at https://github.com/playframework/play/commits/b90a6770427b8ec19149e4ae3af7bbf19b25ca8f

So I am checking this out now on vps17 and am also using that status of play locally. I expect this to be fixed in play itself soon so I am not committing any separate branch or such. The steps to get this to work on your local machine are:
- remove the play directory that was checked out by the setup script
- clone the whole play tree at `git clone git://github.com/playframework/play.git`
- go to the play dir and then `git checkout b90a6770427b8ec19149e4ae3af7bbf19b25ca8f`
- compile play via `cd framework && ant`
- run a play clean on culturehub. if you run a play deps --sync make sure you re-link the scala module by hand (this version of play doesn't support local module repositories) via `cd modules && ln -s ../module-extra/scala-head scala-head`

**Closed as completed** 2011-10-03 08:38 UTC
